### ISSUE TITLE
About supplementary materials

### ISSUE THREAD

**Issue by bit704** [xilongzhou/Adversarial-Single-Image-SVBRDF-Estimation-with-Hybrid-Training#1]
Thanks for your excellent work!
I find that the "Supplement" in the [project page](https://people.engr.tamu.edu/nimak/Papers/EG2021_SVBRDF/index.html) is not available. I wonder if I can get a copy of it, or will the bug be fixed?

**Comment by xilongzhou** [comment]
Hi,

Thanks for pointing this out! we have fixed this!
